package mailer

import (
	"bytes"
	"fmt"
	"html/template"
	"net/smtp"
	"strings"
	"time"
)

// MatchedTender bundles a project with its analysis result for the digest email.
type MatchedTender struct {
	Title       string
	ProcOffice  string
	Location    string
	PubDate     string
	Score       int
	Reasoning   string
	SimapURL    string
	SubType     string
	ProcessType string
}

// Mailer handles sending the digest email via SMTP.
type Mailer struct {
	host, port, user, password, from, to string
}

// New creates a new Mailer.
func New(host, port, user, password, from, to string) *Mailer {
	return &Mailer{host: host, port: port, user: user, password: password, from: from, to: to}
}

const emailTemplate = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body { font-family: Arial, sans-serif; font-size: 14px; color: #333; max-width: 820px; margin: 0 auto; }
  h1 { color: #1a5276; border-bottom: 2px solid #1a5276; padding-bottom: 8px; }
  h2 { color: #2471a3; margin: 0 0 8px 0; font-size: 16px; }
  .tender { background: #f8f9fa; border-left: 4px solid #2471a3; padding: 16px; margin-bottom: 20px; border-radius: 4px; }
  .tender.high { border-left-color: #1e8449; }
  .score { display: inline-block; background: #2471a3; color: #fff; padding: 3px 10px; border-radius: 12px; font-weight: bold; font-size: 13px; }
  .score.high { background: #1e8449; }
  .meta { color: #666; font-size: 12px; margin-top: 8px; line-height: 1.8; }
  .reasoning { margin-top: 10px; background: #fff; padding: 10px; border-radius: 4px; font-style: italic; color: #444; }
  .btn { display: inline-block; background: #1a5276; color: #fff !important; padding: 7px 16px; text-decoration: none; border-radius: 4px; margin-top: 12px; font-size: 13px; }
  .btn:hover { background: #21618c; }
  .empty { color: #888; font-style: italic; }
  .footer { color: #aaa; font-size: 11px; margin-top: 30px; border-top: 1px solid #eee; padding-top: 10px; }
</style>
</head>
<body>
<h1>📡 Project Radar — Tender Digest</h1>
<p>Generated: <strong>{{.GeneratedAt}}</strong> &nbsp;·&nbsp; <strong>{{.Count}}</strong> matching tender(s) found.</p>

{{if .Tenders}}
{{range .Tenders}}
<div class="tender {{if ge .Score 75}}high{{end}}">
  <h2>{{.Title}}</h2>
  <span class="score {{if ge .Score 75}}high{{end}}">Score: {{.Score}} / 100</span>
  <div class="meta">
    🏛 <strong>Authority:</strong> {{.ProcOffice}}<br>
    📍 <strong>Location:</strong> {{.Location}}<br>
    📅 <strong>Published:</strong> {{.PubDate}}<br>
    🏷 <strong>Sub-type:</strong> {{if .SubType}}{{.SubType}}{{else}}—{{end}} &nbsp;·&nbsp;
    ⚙️ <strong>Procedure:</strong> {{.ProcessType}}
  </div>
  <div class="reasoning">💡 {{.Reasoning}}</div>
  <a class="btn" href="{{.SimapURL}}" target="_blank">View on simap.ch →</a>
</div>
{{end}}
{{else}}
<p class="empty">No matching tenders found today. Check back tomorrow!</p>
{{end}}

<div class="footer">
  Automatically generated by <strong>project-radar</strong> · Aiza GmbH · angela.scherer@aiza.ch<br>
  Disclaimer: "This is not an official publication. The authoritative data is published on www.simap.ch."
</div>
</body>
</html>`

type emailData struct {
	GeneratedAt string
	Count       int
	Tenders     []MatchedTender
}

// Send sends the HTML digest email.
func (m *Mailer) Send(tenders []MatchedTender) error {
	tmpl, err := template.New("email").Parse(emailTemplate)
	if err != nil {
		return fmt.Errorf("parse email template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, emailData{
		GeneratedAt: time.Now().Format("02 Jan 2006 15:04"),
		Count:       len(tenders),
		Tenders:     tenders,
	}); err != nil {
		return fmt.Errorf("render email template: %w", err)
	}

	subject := fmt.Sprintf("📡 Project Radar: %d matching tender(s) — %s",
		len(tenders), time.Now().Format("02 Jan 2006"))

	msg := buildMessage(m.from, m.to, subject, buf.String())

	var auth smtp.Auth
	if m.user != "" && m.password != "" {
		auth = smtp.PlainAuth("", m.user, m.password, m.host)
	}

	if err := smtp.SendMail(m.host+":"+m.port, auth, m.from, []string{m.to}, []byte(msg)); err != nil {
		return fmt.Errorf("smtp send: %w", err)
	}
	return nil
}

func buildMessage(from, to, subject, htmlBody string) string {
	var sb strings.Builder
	sb.WriteString("From: " + from + "\r\n")
	sb.WriteString("To: " + to + "\r\n")
	sb.WriteString("Subject: " + subject + "\r\n")
	sb.WriteString("MIME-Version: 1.0\r\n")
	sb.WriteString("Content-Type: text/html; charset=\"UTF-8\"\r\n")
	sb.WriteString("\r\n")
	sb.WriteString(htmlBody)
	return sb.String()
}
